#!/bin/bash

find .                             \
     \(                            \
     -name "*~" -o                 \
     -name "#*#" -o                \
     -name "*.pyc" -o              \
     -name "__pycache__" -o        \
     -name ".vscode" -o            \
     -name "vgcore.*" -o           \
     -name ".idea" -o              \
     -name ".gdb_history" -o       \
     -name "peda-session-*.txt" \) \
     -print -exec rm -rf {} +
