#!/bin/bash

function helps {
    echo -e "USAGE:"
    echo -e "\trepo [Domain] [Repo name]\n"
    echo -e "DESCRIPTION:"
    echo -e "\tDomain\tgithub or epitech depending of where your repo is"
    echo -e "\tRepo name\tthe name of the repository"
}

if [ "$#" -eq 2 ]
then
    if [ $1 = github ]
    then
        url="git@github.com:Breigner01/"
        end=".git"
    elif [ $1 = epitech ]
    then
        url="git@git.epitech.eu:benjamin.reigner@epitech.eu/"
        end=""
    else
        echo -e "\e[38;5;45mUnknown domain\e[0m"
        exit
    fi
    repo=$2
else
    echo -e "\e[38;5;45mWrong number of arguments\e[0m"
    helps
    exit
fi

repo_url=$url$repo$end

git init
git add --all
git commit -m "First commit"
git remote add origin $repo_url
git push -u origin master
